
# For references of usage yaml. etc action/<github actions>: https://github.com/actions

name: TestGithubRunners # this is main title of the runner job
 
on:
  push:
    branches: [ "test-workflows" ] # trigger if someone do push on the main branch
  pull_request:
    branches: [ "test-workflows" ] # trigger if someone do pull request on the main branch

jobs: # mandatory
  first-stage:  # name of the stage also?
      name: this is first stage # name of the stage 
      runs-on: self-hosted #tag from runner

      steps:
      - name: CheckOut Code # name of the step 
        uses: actions/checkout@v4 # checkout@v4 from github/actions repo
        with:
          repository: shahrid92/sr-selenium-framework
          ref: test-workflows

      - name: Test echo work folder # name of the step
        run: ls -la /usr/local/_work

  second-stage:
      name: this is second stage # name of the stage 
      runs-on: self-hosted #tag from runner

      steps:
      - name: build projects
        uses: actions/setup-java@v4
        with:
          java-version: '11' # Specify the Java version
          distribution: 'temurin' # Options: 'temurin', 'zulu', etc.
      - run: java --version

      - name: print working file
        run: pwd && ls -la
