
# For references of usage yaml. etc action/<github actions>: https://github.com/actions

name: TestGithubRunners # this is main title of the runner job
 
on:
  push:
    branches: [ "main" ] # trigger if someone do push on the main branch
  pull_request:
    branches: [ "main" ] # trigger if someone do pull request on the main branch

jobs: # mandatory
  this-is-test-stage:  # name of the stage also?
      name: this is first step # name of the stage 
      runs-on: self-hosted #tag from runner

      steps:
      - name: CheckOut Code # name of the step 
        uses: actions/checkout@v4 # checkout@v4 from github/actions repo
        with:
          repository: shahrid92/sr-selenium-framework
          ref: main

      - name: Test echo # name of the step
        run: ls -la /usr/local
